version: "3.9"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: server

    image: server:local
    ports:
      - "3017:3017"

    environment:
      NODE_ENV: ${NODE_ENV}
    restart: unless-stopped
