import { reactRouter } from "@react-router/dev/vite";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  build: {
    sourcemap: true,
  },

  plugins: [
    reactRouter(),
    // @ts-expect-error Literally errors with the autogenerated code from react-router!
    tsconfigPaths({
      projects: [
        "./tsconfig.json",
        "../application/tsconfig.json",
        "../infrastructure/tsconfig.json",
      ],
    }),
  ],
});
